# Generated by Django 5.2.4 on 2025-07-19 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0004_auto_20190908_1625'),
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('orderNo', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='订单状态')),
                ('address', models.TextField(verbose_name='收货地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payTime', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipTime', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completeTime', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.admin', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 't_Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, verbose_name='订单项ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买时价格')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book', verbose_name='图书')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'db_table': 't_OrderItem',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.admin', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 't_Cart',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
