# Generated by Django 5.2.4 on 2025-07-19 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20190908_1625'),
        ('Index', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='Book.book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Index.admin', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Index.admin', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='Book.book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order', verbose_name='订单'),
        ),
    ]
