# Generated by Django 5.2.4 on 2025-07-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.IntegerField(default=0, help_text='1为管理员，0为普通用户', verbose_name='身份'),
        ),
    ]
